version: '2.2'

networks:
  reporting-network:
    external: true
    
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
    
services: 
  postgres:
    image: debezium/postgres
    container_name: postgres
    depends_on: 
      - zookeeper
      - kafka

    restart: always

    environment:
      - POSTGRES_PASSWORD=mosip123
      - POSTGRES_DB=anonprofile

    ports: 
      - 5432:5432
    
    # to activate WAL 
    command: postgres -c wal_level=logical -c archive_mode=on -c max_wal_senders=5
    
    volumes:
      - shared-workspace:/opt/workspace
      - ./PostgresDB:/docker-entrypoint-initdb.d/
  
  zookeeper:
    image: debezium/zookeeper
    container_name: zookeeper
    volumes:
      - shared-workspace:/opt/workspace
    ports: 
      - 2181:2181
      - 2888:2888 
      - 3888:3888
    
    stdin_open: true
    tty: true

  kafka:
    image: debezium/kafka
    container_name: kafka
    depends_on: 
      - zookeeper
    volumes:
      - shared-workspace:/opt/workspace    
    ports: 
      - 9092:9092
    
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

    stdin_open: true
    tty: true
    links:
     - zookeeper:zookeeper
  
  connect:
    image: debezium/connect
    container_name: connect
    depends_on: 
      - postgres
      - zookeeper
      - kafka
    volumes:
      - shared-workspace:/opt/workspace
    ports:
      - 8083:8083
    
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my-connect-configs
      - OFFSET_STORAGE_TOPIC=my-connect-offsets
      - STATUS_STORAGE_TOPIC=my-connect-statuses
      - ADVERTISED_HOST_NAME=connect
      - BOOTSTRAP_SERVERS=kafka:9092
    
    stdin_open: true
    tty: true
    
    links:
      - zookeeper:zookeeper
      - postgres:postgres  
      - kafka:kafka

  jupyterlab:
    image: spark/jupiterlab:v1
    container_name: jupyterlab
    ports:
     - 8888:8888
    volumes:
     - shared-workspace:/opt/workspace
        

  spark-master:
      image: spark/sparkmaster:v1
      container_name: spark-master
      environment:
       - SPARK_MODE=master
       - SPARK_RPC_AUTHENTICATION_ENABLED=no
       - SPARK_RPC_ENCRYPTION_ENABLED=no
       - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
       - SPARK_SSL_ENABLED=no
      ports:
       - 8080:8080
       - 7077:7077
      volumes:
       - shared-workspace:/opt/workspace
  
  
  spark-worker-1:
      image: spark/sparkworker:v1
      container_name: spark-worker-1
      environment:
       - SPARK_MODE=worker
       - SPARK_MASTER_URL=spark://spark:7077
       - SPARK_WORKER_MEMORY=1G
       - SPARK_WORKER_CORES=1
       - SPARK_RPC_AUTHENTICATION_ENABLED=no
       - SPARK_RPC_ENCRYPTION_ENABLED=no
       - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
       - SPARK_SSL_ENABLED=no
      ports:
       - 8081:8081
      volumes:
       - shared-workspace:/opt/workspace
      depends_on:
       - spark-master
  
  
  spark-worker-2:
      image: spark/sparkworker:v1
      container_name: spark-worker-2
      environment:
       - SPARK_MODE=worker
       - SPARK_MASTER_URL=spark://spark:7077
       - SPARK_WORKER_MEMORY=1G
       - SPARK_WORKER_CORES=1
       - SPARK_RPC_AUTHENTICATION_ENABLED=no
       - SPARK_RPC_ENCRYPTION_ENABLED=no
       - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
       - SPARK_SSL_ENABLED=no
      ports:
       - 8082:8081
      volumes:
       - shared-workspace:/opt/workspace
      depends_on:
       - spark-master